//Main Page
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const START_FETCHING_DATA_PACKAGE = "START_FETCHING_DATA_PACKAGE";
export const END_FETCHING_DATA_PACKAGE = "END_FETCHING_DATA_PACKAGE";

//Decisions
export const GET_PROJECTS = "GET_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const CREATE_EXAMPLE_DATA = "CREATE_EXAMPLE_DATA";
export const TRANSFER_PROJECT_TO_USER = "TRANSFER_PROJECT_TO_USER";

//OptionsAndCriteria
export const GET_ITEMS = "GET_ITEMS";
export const CREATE_ITEM = "CREATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";

//WeightCriteria
export const GET_CRITERIA = "GET_CRITERIA";
export const CHANGE_CRITERIA = "CHANGE_CRITERIA";
export const SEND_EVERY_CRITERIA = "SEND_EVERY_CRITERIA";

//RateOptions
export const GET_OPTIONS = "GET_OPTIONS";
export const CHANGE_OPTION = "CHANGE_OPTION";
export const SEND_EVERY_OPTION = "SEND_EVERY_OPTION";

//Result
export const GET_RESULT = "GET_RESULT";

//Security
export const GET_ERRORS  = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_UNREGISTERED_USERS = "GET_UNREGISTERED_USERS";
export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
