//Main Page
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

//Decisions
export const GET_DECISIONS = "GET_DECISIONS";
export const POST_DECISION = "POST_DECISION";
export const DELETE_DECISION = "DELETE_DECISION";
export const PUT_DECISION = "PUT_DECISION";

//OptionsAndCriteria
export const GET_DECISION_OPTIONS = "GET_DECISION_OPTIONS";
export const POST_DECISION_OPTION = "POST_DECISION_OPTION";
export const DELETE_DECISION_OPTION = "DELETE_DECISION_OPTION";
export const PUT_DECISION_OPTION = "PUT_DECISION_OPTION";

export const GET_SELECTION_CRITERIA = "GET_SELECTION_CRITERIA";
export const POST_SELECTION_CRITERIA = "POST_SELECTION_CRITERIA";
export const DELETE_SELECTION_CRITERIA = "DELETE_SELECTION_CRITERIA";
export const PUT_SELECTION_CRITERIA = "PUT_SELECTION_CRITERIA";


//WeightCriteria
export const GET_WEIGHTED_CRITERIA = "GET_WEIGHTED_CRITERIA";
export const PUT_WEIGHTED_CRITERIA = "PUT_WEIGHTED_CRITERIA";

//RateOptions
export const GET_RATED_OPTIONS = "GET_RATED_OPTIONS";
export const PUT_RATED_OPTION = "PUT_RATED_OPTION";

//Sessions
export const POST_SESSION = "POST_SESSION";
export const POST_USER = "POST_USER";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const DELETE_TOKEN = "DELETE_TOKEN";

//Alerts
export const SHOW_ALERT  = "SHOW_ALERT";
export const DELETE_ALERT  = "DELETE_ALERT";

//Errors
export const SET_ERRORS  = "SET_ERRORS";